;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-abbr-reader.ss" "lang")((modname ex185-list-abbr-test) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(check-expect (first (list 1 2 3))
              1)
(check-expect (rest (list 1 2 3))
              (list 2 3))
(check-expect (second (list 1 2 3))
              2)
(check-expect (third (list 1 2 3))
              3)
(check-expect (fourth (list 1 2 3 4))
              4)
(check-expect (fifth (list 1 2 3 4 5))
              5)