;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname ex441-hand-quick-sort-undergoing) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
;;(quick-sort< (list 10 6 8 9 14 12 3 11 14 16 2))
;;==
;;(append (quick-sort< '(6 8 9 3 2))
;;        '(10)
;;        (quick-sort< '(14 12 11 14 16)))
;;==
;;(append (append (quick-sort< '(3 2))
;;                '(6)
;;                (quick-sort< '(8 9)))
;;        '(10)
;;        (append (quick-sort< '(12 11 14))
;;                '(14)
;;                (quick-sort< '(16))))
;;==
;;(append (append (append (quick-sort< '(2))
;;                        '(3)
;;                        (quick-sort< '()))
;;                '(6)
;;                (append (quick-sort< '())
;;                        '(8)
;;                        (quick-sort< '(9))))
;;        '(10)
;;        (append (append (quick-sort< '(11))
;;                        '(12)
;;                        (quick-sort< '(14)))
;;                '(14)
;;                (quick-sort< '(16))))
;; need 12 quick-sort< and 6 append.
;; the quick-sort< need less than 2^n(n is the list's length),
;; the append need less than n 


;; (quick-sort< (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (quick-sort< '(2 3 4 5 6 7 8 9 10 11 12 13 14)))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (quick-sort< '(3 4 5 6 7 8 9 10 11 12 13 14))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (quick-sort< '(4 5 6 7 8 9 10 11 12 13 14)))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (quick-sort< '(5 6 7 8 9 10 11 12 13 14))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (quick-sort< '(6 7 8 9 10 11 12 13 14)))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (quick-sort< '(7 8 9 10 11 12 13 14))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (quick-sort< '(8 9 10 11 12 13 14)))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (quick-sort< '(9 10 11 12 13 14))))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (append (quick-sort< '())
;;                                                                        '(9)
;;                                                                        (quick-sort< '(10 11 12 13 14)))))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (append (quick-sort< '())
;;                                                                        '(9)
;;                                                                        (append (quick-sort< '())
;;                                                                                '(10)
;;                                                                                (quick-sort< '(11 12 13 14))))))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (append (quick-sort< '())
;;                                                                        '(9)
;;                                                                        (append (quick-sort< '())
;;                                                                                '(10)
;;                                                                                (append (quick-sort< '())
;;                                                                                        '(11)
;;                                                                                        (quick-sort< '(12 13 14)))))))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (append (quick-sort< '())
;;                                                                        '(9)
;;                                                                        (append (quick-sort< '())
;;                                                                                '(10)
;;                                                                                (append (quick-sort< '())
;;                                                                                        '(11)
;;                                                                                        (append (quick-sort< '())
;;                                                                                                '(12)
;;                                                                                                (quick-sort< '(13 14))))))))))))))
;;==
;;(append (quick-sort< '())
;;        '(1)
;;        (append (quick-sort< '())
;;                '(2)
;;                (append (quick-sort< '())
;;                        '(3)
;;                        (append (quick-sort< '())
;;                                '(4)
;;                                (append (quick-sort< '())
;;                                        '(5)
;;                                        (append (quick-sort< '())
;;                                                '(6)
;;                                                (append (quick-sort< '())
;;                                                        '(7)
;;                                                        (append (quick-sort< '())
;;                                                                '(8)
;;                                                                (append (quick-sort< '())
;;                                                                        '(9)
;;                                                                        (append (quick-sort< '())
;;                                                                                '(10)
;;                                                                                (append (quick-sort< '())
;;                                                                                        '(11)
;;                                                                                        (append (quick-sort< '())
;;                                                                                                '(12)
;;                                                                                                (append (quick-sort< '())
;;                                                                                                        '(13)
;;                                                                                                        (quick-sort< '(14)))))))))))))))
;;
;;
;; 13 append, 25 quick-sort<, contradict ...
